### ISSUE TITLE
"Something went wrong internally, reopen and no worries"

### ISSUE THREAD

**Issue by corysimmons** [ricardofbarros/linter-js-standard#179] opened 2017-04-18 15:32 UTC
https://github.com/atom/atom/issues/14248

Happens really frequently for no discernible reason.

**Comment by damon-kreft** [comment] 2017-04-19 01:53
Yeah same here. Consistently the the very first time I open a JS file, whether `standard` is in `devDependencies` or not...

<img width="496" alt="screen shot 2017-04-19 at 02 52 25" src="https://cloud.githubusercontent.com/assets/4972683/25160002/45a9869a-24ab-11e7-800b-45ce19355f51.png">

Here are my Atom settings/packages: https://gist.github.com/damon-kreft/9801de58dce368df4f06b917f317559a

**Comment by dcalhoun** [comment] 2017-04-19 14:08
I can confirm this warning displays when opening the first JavaScript file after creating a new Atom window. It happens every time consistently. After the first JavaScript file is open, the warning does not appear again until I create a new Atom window.

#### Environment
- Atom 1.16.0
- linter 2.1.4
- linter-ui-default 1.2.3
- linter-js-standard 3.9.0
- standard 10.0.1

**Comment by mattfysh** [comment] 2017-05-05 01:02
I don't know enough about atom internals but it looks like `this.cache.get('text-editor', ...` inside of `linter-js-standard.js` is being trigger *before* the call to `this.cache.set...` in `init.js`

**Comment by dcalhoun** [comment] 2017-05-16 12:50
This is a duplicate of #126 and should likely be closed.

**Comment by whaaaley** [comment] 2017-05-18 16:13
@dcalhoun i think this issue differs because:
+ it happens on just the first file opened
+ only one error appears
+ only happens after you start atom and open a file

**Comment by Positive07** [comment] 2017-05-18 17:17
I had this same issue, as @whaaaley explained, it started to happen after my configuration was reset (for some other problem I'm guessing).

I cannot reproduce this consistently though

**Comment by revelt** [comment] 2017-06-20 09:35
Confirmed, it's happening exactly as @whaaaley described. First open of first JS file. Subsequent opens won't trigger the error. I can recreate it, just close the window, open some project, click on the tree view on any JS file, error will appear.

It will appear again and again if you won't double-click-open one JS file and close it. After closing, it does not appear on that window any more.

**Comment by revelt** [comment] 2017-06-20 09:59
Switching to an alternative Standard linter, [linter-js-standard-engine](https://github.com/gustavnikolaj/linter-js-standard-engine) solved this for me.

**Comment by whaaaley** [comment] 2017-06-20 16:29
@revelt Looks nice, however it looks like everything is an error rather than having some warnings, but that's much more tolerable than a message window. I'll be using this from now on too.

**Comment by whaaaley** [comment] 2017-06-23 16:50
@revelt Looks like that project doesn't have html support or support for a global install _or_ a default engine... all of those things are kind of a bummer for me. I might go digging later and try to fix this.

**Comment by whaaaley** [comment] 2017-06-23 16:56
Looks like the PR by @educcjr fixes this! I just cloned and tested it out.

**Comment by sonicdoe** [comment] 2017-07-27 20:24
This will be fixed in an upcoming patch version.

**Closed** 2017-07-27 20:24 UTC

**Comment by sonicdoe** [comment] 2017-07-28 06:01
Released in v3.9.2 🎉

**Comment by revelt** [comment] 2017-07-28 06:05
I can confirm 3.9.2 works perfectly. Thanks everybody!
