### ISSUE TITLE
Uncaught Error: Column start (11) greater than line length (10) for line 114

### ISSUE THREAD

**Issue by oscarojeda** [ricardofbarros/linter-js-standard#203] opened 2017-09-11 15:12 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package 4.0.1

### Stack Trace

Uncaught Error: Column start (11) greater than line length (10) for line 114

```
At C:\Users\oojeda\.atom\packages\linter-js-standard\node_modules\atom-linter\lib\index.js:181

Error: Column start (11) greater than line length (10) for line 114
    at generateRange (/packages/linter-js-standard/node_modules/atom-linter/lib/index.js:181:11)
    at getRange (/packages/linter-js-standard/lib/utils/linter.js:16:10)
    at /packages/linter-js-standard/lib/utils/linter.js:39:19
    at Array.forEach (native)
    at Object.module.exports (/packages/linter-js-standard/lib/utils/linter.js:29:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:47.2.0 core:move-down (input.hidden-input)
  8x -0:47.1.0 core:move-right (input.hidden-input)
     -0:45.7.0 core:move-left (input.hidden-input)
  5x -0:45.2.0 core:backspace (input.hidden-input)
     -0:43.7.0 intentions:highlight (input.hidden-input)
     -0:43.5.0 core:save (input.hidden-input)
     -0:28 core:backspace (input.hidden-input)
     -0:27.3.0 intentions:highlight (input.hidden-input)
     -0:27.2.0 core:save (input.hidden-input)
  2x -0:25.2.0 editor:newline (input.hidden-input)
  2x -0:19 core:page-up (input.hidden-input)
  8x -0:17.5.0 core:page-down (input.hidden-input)
     -0:10 core:backspace (input.hidden-input)
     -0:09.6.0 editor:newline (input.hidden-input)
     -0:09.3.0 intentions:highlight (input.hidden-input)
     -0:09.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.30.5 
atom-hg 2.0.14 
autoclose-html 0.23.0 
autocomplete-angular-material 0.4.0 
busy-signal 1.4.3 
emmet 2.4.3 
intentions 1.1.5 
jsonlint 1.1.4 
linter 2.2.0 
linter-htmlhint 1.3.3 
linter-js-standard 4.0.1 
linter-jsonlint 1.3.0 
linter-php 1.4.0 
linter-ui-default 1.6.8 
platformio-ide-terminal 2.6.0 
```

**Comment by sonicdoe** [comment] 2017-09-12 06:13
Duplicate of #200.

**Closed by sonicdoe** 2017-09-12 06:13 UTC
