### ISSUE TITLE
Stopped linting...

### ISSUE THREAD

**Issue by stephen-last** [ricardofbarros/linter-js-standard#210] opened 2017-11-09 14:39 UTC
I've updated to these versions and now I'm not getting any linting at all:

- `atom 1.22.0 ia32`
- `linter 2.2.0`
- `linter-js-standard 4.0.2`
- `linter-ui-default 1.6.10`

I have `standard 10.0.3` installed in my project, under `devDependencies` in `package.json`.

When editing a `.js` file I get no linter warnings when I deliberately do something like no space after a function name (`function myFunc() {}`).

Why would it not be linting now..?

**Comment by grudra7714** [comment] 2017-11-09 16:23
I don't think it is "syntactically" wrong. What would happen is your myFunc would be out of scope and you have to reference this function to another variable if you have to use it. 

[See this](http://jsbin.com/kegupe/edit?html,console)

**Comment by stephen-last** [comment] 2017-11-09 16:57
@grudra7714 I think you may have misunderstood.

Writing a function without a space after the name should give me a lint error (see [the rules](https://standardjs.com/#the-rules)) when following [JavaScript Standard Style](https://standardjs.com/).

The problem is that Atom isn't linting even with the setup I mentioned.

It's not a code issue.

**Comment by Arcanemagus** [comment] 2017-11-09 17:15
Can you post the output of running `Linter: Debug`? It's possible you installed a custom language file that is making the `foo.js` file not look like `JavaScript` to Atom.

**Comment by stephen-last** [comment] 2017-11-20 08:57
```
Platform: win32
Atom Version: 1.22.0
Linter Version: 2.2.0
Opened file is ignored: No
Matching Linter Providers: 
  - js-standard
Disabled Linter Providers: 
Standard Linter Providers: 
  - js-standard
Indie Linter Providers: 
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - source.js
```

**Comment by vincenzoml** [comment] 2017-11-20 13:44
I have the same bug on a fresh installation. Since I had installed many packages, I deleted my ~/.atom entirely (is that sufficient or are there other places where config is saved?). linter-js-standard lints html embedded script, but not .js files...

**Comment by vincenzoml** [comment] 2017-11-20 13:49
Platform: linux
Atom Version: 1.22.1
Linter Version: 2.2.0
Opened file is ignored: No
Matching Linter Providers: 
  - js-standard
Disabled Linter Providers: 
Standard Linter Providers: 
  - js-standard
Indie Linter Providers: 
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - source.js
  - meta.method-call.js
  - meta.arguments.js

**Comment by sonicdoe** [comment] 2017-11-26 15:09
I’ve tried to reproduce this on a fresh Ubuntu installation with Atom v1.22.0, `linter@2.2.0`, `linter-js-standard@4.0.2`, and `linter-ui-default@1.6.10` (as specified in your original post) but I did not run into this issue.

A few questions:

- Does running `standard` from the command line work?
- Do you have any custom `standard` settings in your `package.json`?
- Could you try installing `linter-js-standard@3.9.3` to see if this bug has been introduced in one of the recent versions?

@vincenzoml Your issue seems to be different since the linter produces some errors, at least. Would you mind opening a new issue for that?

**Comment by vincenzoml** [comment] 2017-11-26 17:35
As soon as I return to my main machine I'll check and open a new issue.

**Comment by sonicdoe** [comment] 2018-06-11 19:11
If anyone is still running into this issue, let me and I’ll reopen.

**Closed by sonicdoe** 2018-06-11 19:11 UTC

**Comment by sonicdoe** [comment] 2018-06-22 11:17
linter-js-standard v5.1.0 adds support for Atom’s experimental Tree-sitter parsing system, see https://github.com/ricardofbarros/linter-js-standard/commit/46c803841d61a720aa45d72234fe7ac8267c531b.
