### ISSUE TITLE
Cannot install on Ubuntu due to npm error “cb() never called”

### ISSUE THREAD

**Issue by ukaaa** [ricardofbarros/linter-js-standard#192] opened 2017-07-14 09:54 UTC
This issue has been reported multiple times, but the last response was a year ago. 
I have this same issue today on Ubuntu.

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! cb() never called!
```

```
➜ apm -v
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4

➜ node -v
v6.11.0

➜ npm -v
4.6.1
```
Not sure if this is related to the issue, but:

```
➜ npm ls minimatch -g
├─┬ commitizen@2.9.6
│ └─┬ glob@7.1.1
│   └── minimatch@3.0.4 
├─┬ gulp@3.9.1
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ glob-stream@3.1.18
│   │ ├─┬ glob@4.5.3
│   │ │ └── minimatch@2.0.10  deduped
│   │ └── minimatch@2.0.10 
│   └─┬ glob-watcher@0.0.6
│     └─┬ gaze@0.5.2
│       └─┬ globule@0.1.0
│         ├─┬ glob@3.1.21
│         │ └── minimatch@0.2.14  deduped
│         └── minimatch@0.2.14 
└─┬ npm@4.6.1
  ├─┬ fstream-npm@1.2.0
  │ └─┬ fstream-ignore@1.0.5
  │   └── minimatch@3.0.3 
  ├─┬ glob@7.1.1
  │ └── minimatch@3.0.3 
  └─┬ node-gyp@3.6.0
    └── minimatch@3.0.3 
```

**Comment by sonicdoe** [comment] 2017-07-29 10:39
Can you reliably reproduce this? What command are you executing (e.g. `apm install linter-js-standard`)?

> This issue has been reported multiple times, but the last response was a year ago.

Could you link to those issues?

**Comment by ukaaa** [comment] 2017-07-31 07:20
Yes I'm using `apm install linter-js-standard` to reproduce this error.
The issues [I found](https://github.com/ricardofbarros/linter-js-standard/issues?utf8=%E2%9C%93&q=is%3Aissue%20minimatch%20) are for Windows though, and it was said to be fixed in Atom beta or in a newer Atom release. I'm not sure if that's the same for Ubuntu?

**Comment by sonicdoe** [comment] 2017-07-31 19:03
The other issues are not the same as this one. The `minimatch` line is just a deprecation warning ([already updated on `master`](https://github.com/ricardofbarros/linter-js-standard/commit/18d8148e717a97b153303535a47f1043e94583b8)) and should not cause the `cb() never called!` error.  However, I have found a [similar issue on the Atom forum](https://discuss.atom.io/t/atom-error-on-installing-upgrading-packages/42600) (unfortunately, unanswered).

Please check if `~/.atom/packages/linter-js-standard` already exists and remove it, if so. Then, try `apm install linter-js-standard` again.

If this didn’t work, please try:

```sh
cd ~/.atom/packages
rm -rf linter-js-standard && mkdir linter-js-standard && cd linter-js-standard
curl -L https://github.com/ricardofbarros/linter-js-standard/archive/v3.9.3.tar.gz | tar xzf - --strip 1
npm install
```

This will download linter-js-standard directly from GitHub and install any dependencies using your own npm version. While this is not a solution, I’m interested if this workaround works.

**Comment by ukaaa** [comment] 2017-08-02 08:32
Downloading it straight from GitHub works @sonicdoe! I still get the deprecation warning but not the “cb() never called” error. The linter is now present in Atom and working.

**Comment by sonicdoe** [comment] 2017-08-02 18:11
Thanks, not the answer I was hoping for but the one I was expecting 😀

I’ll close this issue now since it doesn’t seem to be directly caused by linter-js-standard. Feel free to open an issue over at [atom/atom](https://github.com/atom/atom) or [atom/apm](https://github.com/atom/apm).

**Closed by sonicdoe** 2017-08-02 18:11 UTC

**Comment by ukaaa** [comment] 2017-08-02 18:16
OK. Thanks for your time @sonicdoe, I found it was difficult to judge how relevant this issue was.

**Comment by usemoslinux** [comment] 2018-01-23 19:46
The same is happening to me with all Javascript linters. I always get "npm ERR! cb() never called!". I am using Ubuntu 17.10, by the way.
