### ISSUE TITLE
Uncaught Error: Column start (8) greater than line length (0) for line 41

### ISSUE THREAD

**Issue by fernandohg97** [ricardofbarros/linter-js-standard#205] opened 2017-09-11 21:43 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package 4.0.1

### Stack Trace

Uncaught Error: Column start (8) greater than line length (0) for line 41

```
At C:\Users\FER\.atom\packages\linter-js-standard\node_modules\atom-linter\lib\index.js:181

Error: Column start (8) greater than line length (0) for line 41
    at generateRange (/packages/linter-js-standard/node_modules/atom-linter/lib/index.js:181:11)
    at getRange (/packages/linter-js-standard/lib/utils/linter.js:16:10)
    at /packages/linter-js-standard/lib/utils/linter.js:39:19
    at Array.forEach (native)
    at Object.module.exports (/packages/linter-js-standard/lib/utils/linter.js:29:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.4.0 
ariake-dark-syntax 0.1.3 
atom-beautify 0.30.5 
atom-dark-fusion-syntax 2.2.0 
atom-material-syntax 1.0.6 
atom-ternjs 0.18.3 
aurora-theme 1.2.2 
autocomplete-json 5.5.0 
busy-signal 1.4.3 
color-picker 2.2.5 
eclectic-syntax 0.3.0 
emmet 2.4.3 
file-icons 2.1.11 
flexible-ui 0.10.7 
intentions 1.1.5 
language-babel 2.74.1 
language-javascript-better 1.7.1 
linter 2.2.0 
linter-js-standard 4.0.1 
linter-ui-default 1.6.8 
loved-syntax 1.0.2 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
now-syntax 0.2.4 
nucleus-dark-ui 0.12.3 
open-html-in-browser 0.2.0 
pigments 0.40.2 
pristine-ui 1.1.7 
pure-syntax 0.3.0 
quick-highlight 0.10.0 
seti-ui 1.9.0 
standard-formatter 2.8.0 
```

**Comment by sonicdoe** [comment] 2017-09-12 06:18
Duplicate of #200.

**Closed by sonicdoe** 2017-09-12 06:18 UTC
