### ISSUE TITLE
Uncaught Error: Column start (1) greater than line length (0) for line 20

### ISSUE THREAD

**Issue by thejimnicholson** [ricardofbarros/linter-js-standard#204] opened 2017-09-11 16:56 UTC
[Enter steps to reproduce:]

1. Edit a .js file
2. Press return several times to open up blank lines

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) package 4.0.1

### Stack Trace

Uncaught Error: Column start (1) greater than line length (0) for line 20

```
At C:\Users\s003848\.atom\packages\linter-js-standard\node_modules\atom-linter\lib\index.js:181

Error: Column start (1) greater than line length (0) for line 20
    at generateRange (/packages/linter-js-standard/node_modules/atom-linter/lib/index.js:181:11)
    at getRange (/packages/linter-js-standard/lib/utils/linter.js:16:10)
    at /packages/linter-js-standard/lib/utils/linter.js:39:19
    at Array.forEach (native)
    at Object.module.exports (/packages/linter-js-standard/lib/utils/linter.js:29:8)
    at /packages/linter-js-standard/node_modules/standard-flow/node_modules/standard-engine/index.js:180:5
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -3:36.8.0 intentions:highlight (input.hidden-input)
     -3:36.6.0 core:save (input.hidden-input)
     -2:43.5.0 intentions:highlight (input.hidden-input)
     -2:43.1.0 core:save (input.hidden-input)
     -1:51.5.0 intentions:highlight (input.hidden-input)
     -1:51.4.0 core:save (input.hidden-input)
     -1:14.7.0 tree-view:move (span.name.icon.icon-file-text)
  5x -1:12 core:backspace (input.hidden-input)
     -1:07.8.0 core:confirm (input.hidden-input)
     -1:01.9.0 tree-view:move (span.name.icon.icon-file-text)
     -0:58.1.0 core:confirm (input.hidden-input)
     -0:23.9.0 intentions:highlight (input.hidden-input)
     -0:23.7.0 core:copy (input.hidden-input)
  2x -0:17.3.0 editor:newline (input.hidden-input)
  2x -0:16.7.0 core:move-up (input.hidden-input)
     -0:14.7.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
git-plus 7.9.3 
intentions 1.1.5 
language-unix-shell 0.40.1 
linter 2.2.0 
linter-javac 1.9.4 
linter-js-standard 4.0.1 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.8 
pure-syntax 0.3.0 
```

**Comment by sonicdoe** [comment] 2017-09-12 06:17
Thank you for reporting! I’ll track this in #200 since this is a duplicate of #200.

**Closed by sonicdoe** 2017-09-12 06:17 UTC
